export enum IngredientName {
    Twigs = "Twigs",
    DorsalFin = "Dorsal Fin",
    WeevoleCarapace = "Weevole Carapace",
    BoneShards = "Bone Shards",
    Carrot = "Carrot",
    CookedCarrot = "Cooked Carrot",
    Corn = "Corn",
    Popcorn = "Popcorn",
    Eggplant = "Eggplant",
    CookedEggplant = "Braised Eggplant",
    Pumpkin = "Pumpkin",
    CookedPumpkin = "Hot Pumpkin",
    Bluecap = "Blue Cap",
    CookedBluecap = "Cooked Blue Cap",
    Greencap = "Green Cap",
    CookedGreencap = "Cooked Green Cap",
    Redcap = "Red Cap",
    CookedRedcap = "Cooked Red Cap",
    Mandrake = "Mandrake",
    CookedMandrake = "Cooked Mandrake",
    Lichen = "Lichen",
    Cactus = "Cactus Flesh",
    CookedCactus = "Cooked Cactus Flesh",
    CactusFlower = "Cactus Flower",
    Seaweed = "Seaweed",
    CookedSeaweed = "Roasted Seaweed",
    DriedSeaweed = "Dried Seaweed",
    SweetPotato = "Sweet Potato",
    CookedSweetPotato = "Cooked Sweet Potato",
    Aloe = "Aloe",
    CookedAloe = "Cooked Aloe",
    Asparagus = "Asparagus",
    CookedAsparagus = "Cooked Asparagus",
    Radish = "Radish",
    CookedRadish = "Cooked Radish",
    Morsel = "Morsel",
    CookedMorsel = "Cooked Morsel",
    SmallJerky = "Small Jerky",
    Drumstick = "Drumstick",
    CookedDrumstick = "Fried Drumstick",
    Eel = "Eel",
    CookedEel = "Cooked Eel",
    Fish = "Fish",
    CookedFish = "Cooked Fish",
    FrogLegs = "Frog Legs",
    CookedFrogLegs = "Cooked Frog Legs",
    Meat = "Meat",
    CookedMeat = "Cooked Meat",
    Jerky = "Jerky",
    MonsterMeat = "Monster Meat",
    CookedMonsterMeat = "Cooked Monster Meat",
    MonsterJerky = "Monster Jerky",
    DeadDogfish = "Dead Dogfish",
    RawFish = "Raw Fish",
    FishSteak = "Fish Steak",
    NeonQuattro = "Neon Quattro",
    CookedNeonQuattro = "Cooked Neon Quattro",
    PierrotFish = "Pierrot Fish",
    CookedPierrotFish = "Cooked Pierrot Fish",
    PurpleGrouper = "Purple Grouper",
    CookedPurpleGrouper = "Cooked Purple Grouper",
    Roe = "Roe",
    CookedRoe = "Cooked Roe",
    SharkFin = "Shark Fin",
    TropicalFish = "Tropical Fish",
    FishMorsel = "Fish Morsel",
    CookedFishMorsel = "Cooked Fish Morsel",
    Wobster = "Wobster",
    Crabbit = "Crabbit",
    Jellyfish = "Jellyfish",
    DeadJellyfish = "Dead Jellyfish",
    CookedJellyfish = "Cooked Jellyfish",
    DriedJellyfish = "Dried Jellyfish",
    Limpets = "Limpets",
    CookedLimpets = "Cooked Limpets",
    Mussel = "Mussel",
    CookedMussel = "Cooked Mussel",
}


export const inedibleNames = [
    IngredientName.Twigs, 
    IngredientName.DorsalFin,
    IngredientName.WeevoleCarapace,
    IngredientName.BoneShards,
]