export enum IngredientName {
    Morsel = "Morsel",
    CookedMorsel = "Cooked Morsel",
    Twigs = "Twigs",
    DorsalFin = "Dorsal Fin",
    WeevoleCarapace = "Weevole Carapace",
    BoneShards = "Bone Shards",
    Carrot = "Carrot",
    CookedCarrot = "Cooked Carrot",
    Corn = "Corn",
    Popcorn = "Popcorn",
    Eggplant = "Eggplant",
    CookedEggplant = "Braised Eggplant",
    Pumpkin = "Pumpkin",
    CookedPumpkin = "Hot Pumpkin",
    Bluecap = "Blue Cap",
    CookedBluecap = "Cooked Blue Cap",
    Greencap = "Green Cap",
    CookedGreencap = "Cooked Green Cap",
    Redcap = "Red Cap",
    CookedRedcap = "Cooked Red Cap",
    Mandrake = "Mandrake",
    CookedMandrake = "Cooked Mandrake",
    Lichen = "Lichen",
    Cactus = "Cactus Flesh",
    CookedCactus = "Cooked Cactus Flesh",
    CactusFlower = "Cactus Flower",
    Seaweed = "Seaweed",
    CookedSeaweed = "Roasted Seaweed",
    DriedSeaweed = "Dried Seaweed",
    SweetPotato = "Sweet Potato",
    CookedSweetPotato = "Cooked Sweet Potato",
    Aloe = "Aloe",
    CookedAloe = "Cooked Aloe",
    Asparagus = "Asparagus",
    CookedAsparagus = "Cooked Asparagus",
    Radish = "Radish",
    CookedRadish = "Cooked Radish",
}


export const inedibleNames = [
    IngredientName.Twigs, 
    IngredientName.DorsalFin,
    IngredientName.WeevoleCarapace,
    IngredientName.BoneShards,
]